import React, { createContext, useContext, useState, useEffect } from 'react';

const AppContext = createContext();

const MILLETS_DATABASE = [
  {
    id: 'pearl-grain',
    name: 'Organic Pearl Millet Grain',
    tamilName: 'Kambu',
    scientificName: 'Pennisetum glaucum',
    type: 'Major',
    form: 'Raw Grain',
    category: 'Millet Grain',
    subCategory: 'Heritage Unpolished Grains',
    moq: '1 kg',
    pricePerKg: 180,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.9,
    reviewsCount: 142,
    purity: '99.9% Sortex Clean',
    moisture: '< 11.5% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '11.8g / 100g',
    fiber: '8.5g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Heritage high-density grain cultivated in pristine, nutrient-rich soils. Sorted using ultra-precise optical sorters to guarantee unparalleled purity for premium culinary standards.',
    image: '/pearl_millet.png',
    premiumMetric: 'High Iron & Zinc Content',
    inStock: true
  },
  {
    id: 'finger-flour',
    name: 'Heritage Finger Millet Flour',
    tamilName: 'Ragi',
    scientificName: 'Eleusine coracana',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Millet Flour',
    subCategory: 'Premium Stone-Ground Flours',
    moq: '1 kg',
    pricePerKg: 160,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.8,
    reviewsCount: 118,
    purity: '99.8% Stone-Ground Superfine',
    moisture: '< 10.0% Max',
    origin: 'Cumbum Valley Foothills',
    protein: '7.3g / 100g',
    fiber: '11.2g / 100g',
    certification: 'NPOP Organic Certified',
    description: 'Slow stone-ground red millet flour processed under chilled temperatures to retain dietary fibers, calcium, and delicate structural nutrients. Optimal for premium home bakery.',
    image: '/finger_millet.png',
    premiumMetric: 'Elite Dietary Calcium',
    inStock: true
  },
  {
    id: 'foxtail-flakes',
    name: 'Golden Foxtail Millet Flakes',
    tamilName: 'Thinai',
    scientificName: 'Setaria italica',
    type: 'Minor',
    form: 'Flakes',
    category: 'Millet Flakes',
    subCategory: 'Heritage Poha / Flakes',
    moq: '500 g',
    pricePerKg: 210,
    availableSizes: [0.5, 1, 2],
    rating: 4.9,
    reviewsCount: 95,
    purity: '99.9% Steam-Rolled',
    moisture: '< 9.5% Max',
    origin: 'Lower Cumbum Highlands',
    protein: '12.3g / 100g',
    fiber: '8.0g / 100g',
    certification: 'USDA & EU Organic',
    description: 'Lightly parboiled and precision flat-rolled heritage foxtail grains. Delivers an exquisite nutty aroma and perfect structural integrity for nourishing breakfasts.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Low Glycemic Index',
    inStock: true
  },
  {
    id: 'barnyard-grain',
    name: 'Organic Unpolished Barnyard Grain',
    tamilName: 'Kuthiraivali',
    scientificName: 'Echinochloa frumentacea',
    type: 'Minor',
    form: 'Raw Grain',
    category: 'Millet Grain',
    subCategory: 'Heritage Unpolished Grains',
    moq: '1 kg',
    pricePerKg: 190,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.8,
    reviewsCount: 84,
    purity: '99.9% Sortex Clean',
    moisture: '< 11.0% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '11.2g / 100g',
    fiber: '10.1g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Unpolished ancient Barnyard millet, rich in fiber and low-GI carbohydrates. Retains the natural bran layer for maximum nutrient density and exceptional taste.',
    image: '/pearl_millet.png',
    premiumMetric: 'High In Soluble Fiber',
    inStock: true
  },
  {
    id: 'foxtail-grain',
    name: 'Organic Unpolished Foxtail Grain',
    tamilName: 'Thinai',
    scientificName: 'Setaria italica',
    type: 'Minor',
    form: 'Raw Grain',
    category: 'Millet Grain',
    subCategory: 'Heritage Unpolished Grains',
    moq: '1 kg',
    pricePerKg: 185,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.9,
    reviewsCount: 92,
    purity: '99.9% Sortex Clean',
    moisture: '< 11.2% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '12.3g / 100g',
    fiber: '8.0g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Premium quality golden unpolished foxtail millet grain. An ancient staple packed with vitamin B12 and high-quality protein for premium healthy diets.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Rich in Vitamin B12',
    inStock: true
  },
  {
    id: 'ragi-grain',
    name: 'Organic Unpolished Ragi Grain',
    tamilName: 'Ragi',
    scientificName: 'Eleusine coracana',
    type: 'Major',
    form: 'Raw Grain',
    category: 'Millet Grain',
    subCategory: 'Heritage Unpolished Grains',
    moq: '1 kg',
    pricePerKg: 155,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.8,
    reviewsCount: 104,
    purity: '99.8% Sorted',
    moisture: '< 10.5% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '7.3g / 100g',
    fiber: '11.2g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Ancient red finger millet grains sourced directly from heritage farmers. Exceptionally high in calcium, making it a critical health builder.',
    image: '/finger_millet.png',
    premiumMetric: 'Unrivaled Calcium Source',
    inStock: true
  },
  {
    id: 'kodo-grain',
    name: 'Organic Unpolished Kodo Grain',
    tamilName: 'Varagu',
    scientificName: 'Paspalum scrobiculatum',
    type: 'Minor',
    form: 'Raw Grain',
    category: 'Millet Grain',
    subCategory: 'Heritage Unpolished Grains',
    moq: '1 kg',
    pricePerKg: 195,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.7,
    reviewsCount: 73,
    purity: '99.9% Sortex Clean',
    moisture: '< 11.5% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '8.3g / 100g',
    fiber: '9.0g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Unpolished Kodo millet, rich in antioxidants and polyphenols. Cultivated under strict organic rainfed farming standards.',
    image: '/pearl_millet.png',
    premiumMetric: 'Rich in Polyphenols',
    inStock: true
  },
  {
    id: 'proso-grain',
    name: 'Organic Unpolished Proso Grain',
    tamilName: 'Panivaragu',
    scientificName: 'Panicum miliaceum',
    type: 'Minor',
    form: 'Raw Grain',
    category: 'Millet Grain',
    subCategory: 'Heritage Unpolished Grains',
    moq: '1 kg',
    pricePerKg: 175,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.6,
    reviewsCount: 48,
    purity: '99.9% Cleaned',
    moisture: '< 11.0% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '12.5g / 100g',
    fiber: '7.8g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Pure, organic Proso millet grain, which has one of the highest protein contents among small millets. Highly nutritious and gluten-free.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Elite Protein Content',
    inStock: true
  },
  {
    id: 'little-grain',
    name: 'Organic Unpolished Little Grain',
    tamilName: 'Samai',
    scientificName: 'Panicum sumatrense',
    type: 'Minor',
    form: 'Raw Grain',
    category: 'Millet Grain',
    subCategory: 'Heritage Unpolished Grains',
    moq: '1 kg',
    pricePerKg: 180,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.8,
    reviewsCount: 89,
    purity: '99.9% Sortex Clean',
    moisture: '< 10.8% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '7.7g / 100g',
    fiber: '7.6g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Naturally unpolished Little millet grains. An excellent substitute for rice, providing long-lasting energy and slow-release carbohydrates.',
    image: '/pearl_millet.png',
    premiumMetric: 'Low Glycemic Staple',
    inStock: true
  },
  {
    id: 'browntop-grain',
    name: 'Organic Unpolished Browntop Grain',
    tamilName: 'Kula Samai',
    scientificName: 'Urochloa ramosa',
    type: 'Minor',
    form: 'Raw Grain',
    category: 'Millet Grain',
    subCategory: 'Heritage Unpolished Grains',
    moq: '1 kg',
    pricePerKg: 220,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.9,
    reviewsCount: 62,
    purity: '99.9% Cleaned',
    moisture: '< 11.2% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '11.5g / 100g',
    fiber: '12.5g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Ultra-premium unpolished Browntop millet, famous for having the highest dietary fiber content among all millet grains.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Highest Fiber Content',
    inStock: true
  },
  {
    id: 'jowar-grain',
    name: 'Organic Unpolished Jowar Grain',
    tamilName: 'Cholam',
    scientificName: 'Sorghum bicolor',
    type: 'Major',
    form: 'Raw Grain',
    category: 'Millet Grain',
    subCategory: 'Heritage Unpolished Grains',
    moq: '1 kg',
    pricePerKg: 165,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.7,
    reviewsCount: 78,
    purity: '99.8% Sortex',
    moisture: '< 10.8% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '10.4g / 100g',
    fiber: '6.7g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Premium organic white sorghum (Jowar) grains. Perfect for preparing traditional rotis, porridges, and healthy sprouted mixes.',
    image: '/pearl_millet.png',
    premiumMetric: 'Excellent For Rotis',
    inStock: true
  },
  {
    id: 'bajra-grain',
    name: 'Organic Unpolished Bajra Grain',
    tamilName: 'Kambu',
    scientificName: 'Pennisetum glaucum',
    type: 'Major',
    form: 'Raw Grain',
    category: 'Millet Grain',
    subCategory: 'Heritage Unpolished Grains',
    moq: '1 kg',
    pricePerKg: 160,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.8,
    reviewsCount: 112,
    purity: '99.9% Cleaned',
    moisture: '< 11.0% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '11.6g / 100g',
    fiber: '8.5g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Organic unpolished pearl millet (Bajra) grain, rich in iron, zinc, and magnesium. Essential for physical vigor and high energy.',
    image: '/pearl_millet.png',
    premiumMetric: 'High Iron and Zinc',
    inStock: true
  },
  {
    id: 'amaranth-grain',
    name: 'Organic Unpolished Amaranth',
    tamilName: 'Rajgira',
    scientificName: 'Amaranthus',
    type: 'Major',
    form: 'Raw Grain',
    category: 'Millet Grain',
    subCategory: 'Heritage Unpolished Grains',
    moq: '1 kg',
    pricePerKg: 240,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.9,
    reviewsCount: 54,
    purity: '99.9% Cleaned',
    moisture: '< 10.0% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '13.6g / 100g',
    fiber: '7.0g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Exquisite, highly nutritious organic Amaranth seeds. Contains a complete protein profile with all 9 essential amino acids including lysine.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Complete Amino Acids',
    inStock: true
  },
  {
    id: 'barley-grain',
    name: 'Organic Unpolished Barley',
    tamilName: 'Vaarkothumai',
    scientificName: 'Hordeum vulgare',
    type: 'Major',
    form: 'Raw Grain',
    category: 'Millet Grain',
    subCategory: 'Heritage Unpolished Grains',
    moq: '1 kg',
    pricePerKg: 180,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.7,
    reviewsCount: 65,
    purity: '99.8% Sorted',
    moisture: '< 11.5% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '12.5g / 100g',
    fiber: '17.3g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Traditional unpolished barley grains containing premium beta-glucans. Helps regulate digestion and cardiovascular health.',
    image: '/pearl_millet.png',
    premiumMetric: 'Rich in Beta-Glucans',
    inStock: true
  },
  {
    id: 'quinoa-grain',
    name: 'Organic Unpolished White Quinoa',
    tamilName: 'Quinoa',
    scientificName: 'Chenopodium quinoa',
    type: 'Major',
    form: 'Raw Grain',
    category: 'Millet Grain',
    subCategory: 'Heritage Unpolished Grains',
    moq: '1 kg',
    pricePerKg: 290,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.9,
    reviewsCount: 88,
    purity: '99.9% Sortex',
    moisture: '< 9.8% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '14.1g / 100g',
    fiber: '7.0g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Premium quality organic white quinoa seeds, thoroughly pre-washed to remove bitter saponin. Superb protein alternative.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Premium Superfood',
    inStock: true
  },
  {
    id: 'foxtail-flour',
    name: 'Organic Foxtail Millet Flour',
    tamilName: 'Thinai Maavu',
    scientificName: 'Setaria italica',
    type: 'Minor',
    form: 'Fine Flour',
    category: 'Millet Flour',
    subCategory: 'Premium Stone-Ground Flours',
    moq: '1 kg',
    pricePerKg: 200,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.8,
    reviewsCount: 76,
    purity: 'Stone-Ground 99.8%',
    moisture: '< 10.0% Max',
    origin: 'Cumbum Valley Foothills',
    protein: '12.0g / 100g',
    fiber: '8.2g / 100g',
    certification: 'NPOP Organic',
    description: 'Slow-milled organic foxtail millet flour, excellent for making nutritious, mineral-rich rotis and soft idiyappams.',
    image: '/finger_millet.png',
    premiumMetric: 'Stone-Ground Nutrients',
    inStock: true
  },
  {
    id: 'kodo-flour',
    name: 'Organic Kodo Millet Flour',
    tamilName: 'Varagu Maavu',
    scientificName: 'Paspalum scrobiculatum',
    type: 'Minor',
    form: 'Fine Flour',
    category: 'Millet Flour',
    subCategory: 'Premium Stone-Ground Flours',
    moq: '1 kg',
    pricePerKg: 210,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.7,
    reviewsCount: 52,
    purity: 'Stone-Ground 99.9%',
    moisture: '< 9.5% Max',
    origin: 'Cumbum Valley Foothills',
    protein: '8.0g / 100g',
    fiber: '9.2g / 100g',
    certification: 'NPOP Organic',
    description: 'Freshly pulverized unpolished Kodo millet flour. An excellent gluten-free baking base loaded with ancient antioxidants.',
    image: '/finger_millet.png',
    premiumMetric: 'Gluten-Free Baking',
    inStock: true
  },
  {
    id: 'proso-flour',
    name: 'Organic Proso Millet Flour',
    tamilName: 'Panivaragu Maavu',
    scientificName: 'Panicum miliaceum',
    type: 'Minor',
    form: 'Fine Flour',
    category: 'Millet Flour',
    subCategory: 'Premium Stone-Ground Flours',
    moq: '1 kg',
    pricePerKg: 195,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.6,
    reviewsCount: 39,
    purity: 'Superfine Mesh',
    moisture: '< 10.0% Max',
    origin: 'Cumbum Valley Foothills',
    protein: '12.2g / 100g',
    fiber: '7.5g / 100g',
    certification: 'NPOP Organic',
    description: 'High-protein organic Proso flour. Offers a beautiful light texture and subtle nutty flavor for premium biscuits and bread.',
    image: '/finger_millet.png',
    premiumMetric: 'Light Nutty Texture',
    inStock: true
  },
  {
    id: 'jowar-flour',
    name: 'Organic Jowar Millet Flour',
    tamilName: 'Cholam Maavu',
    scientificName: 'Sorghum bicolor',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Millet Flour',
    subCategory: 'Premium Stone-Ground Flours',
    moq: '1 kg',
    pricePerKg: 180,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.8,
    reviewsCount: 97,
    purity: 'Superfine Mesh',
    moisture: '< 10.5% Max',
    origin: 'Cumbum Valley Foothills',
    protein: '10.1g / 100g',
    fiber: '6.5g / 100g',
    certification: 'NPOP Organic',
    description: '100% stone-ground white sorghum flour. Known for high digestibility and perfect soft binding in sugar-free baking.',
    image: '/finger_millet.png',
    premiumMetric: 'Digestible Superfine',
    inStock: true
  },
  {
    id: 'ragi-flour',
    name: 'Organic Ragi Millet Flour',
    tamilName: 'Ragi Maavu',
    scientificName: 'Eleusine coracana',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Millet Flour',
    subCategory: 'Premium Stone-Ground Flours',
    moq: '1 kg',
    pricePerKg: 165,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.9,
    reviewsCount: 143,
    purity: 'Stone-Ground 99.9%',
    moisture: '< 9.8% Max',
    origin: 'Cumbum Valley Foothills',
    protein: '7.2g / 100g',
    fiber: '11.5g / 100g',
    certification: 'NPOP Organic',
    description: 'Rich, red finger millet flour slow stone-ground at low temperatures. Ideal for delicious infant porridge, malt drinks, and soft rotis.',
    image: '/finger_millet.png',
    premiumMetric: 'Optimal Infant Nutrition',
    inStock: true
  },
  {
    id: 'browntop-flour',
    name: 'Organic Browntop Millet Flour',
    tamilName: 'Kula Samai Maavu',
    scientificName: 'Urochloa ramosa',
    type: 'Minor',
    form: 'Fine Flour',
    category: 'Millet Flour',
    subCategory: 'Premium Stone-Ground Flours',
    moq: '1 kg',
    pricePerKg: 240,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.9,
    reviewsCount: 45,
    purity: 'Superfine 99.8%',
    moisture: '< 10.2% Max',
    origin: 'Cumbum Valley Foothills',
    protein: '11.3g / 100g',
    fiber: '12.0g / 100g',
    certification: 'NPOP Organic',
    description: 'A nutritional powerhouse. Extremely high-fiber Browntop millet flour, milled under strict quality supervision for premium diets.',
    image: '/finger_millet.png',
    premiumMetric: 'High-Density Prebiotics',
    inStock: true
  },
  {
    id: 'bajra-flour',
    name: 'Organic Bajra Millet Flour',
    tamilName: 'Kambu Maavu',
    scientificName: 'Pennisetum glaucum',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Millet Flour',
    subCategory: 'Premium Stone-Ground Flours',
    moq: '1 kg',
    pricePerKg: 175,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.8,
    reviewsCount: 88,
    purity: 'Stone-Ground Clean',
    moisture: '< 10.5% Max',
    origin: 'Cumbum Valley Foothills',
    protein: '11.5g / 100g',
    fiber: '8.2g / 100g',
    certification: 'NPOP Organic',
    description: 'Organic pearl millet flour, highly valued for warm climate vitality. Naturally loaded with premium plant-based iron.',
    image: '/finger_millet.png',
    premiumMetric: 'Superior Iron Binding',
    inStock: true
  },
  {
    id: 'barnyard-flour',
    name: 'Organic Barnyard Millet Flour',
    tamilName: 'Kuthiraivali Maavu',
    scientificName: 'Echinochloa frumentacea',
    type: 'Minor',
    form: 'Fine Flour',
    category: 'Millet Flour',
    subCategory: 'Premium Stone-Ground Flours',
    moq: '1 kg',
    pricePerKg: 210,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.8,
    reviewsCount: 67,
    purity: '99.8% Stone-Ground',
    moisture: '< 10.0% Max',
    origin: 'Cumbum Valley Foothills',
    protein: '11.0g / 100g',
    fiber: '10.0g / 100g',
    certification: 'NPOP Organic',
    description: 'Light, fluffy, stone-ground barnyard millet flour. Highly digestible and ideal for delicious, low-GI pancakes and crepes.',
    image: '/finger_millet.png',
    premiumMetric: 'Fluffy Baking Mesh',
    inStock: true
  },
  {
    id: 'mix-flour',
    name: 'Organic Mix Flour Gluten Free',
    tamilName: 'Kalantha Maavu',
    scientificName: 'Multi-grain mix',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Millet Flour',
    subCategory: 'Premium Stone-Ground Flours',
    moq: '1 kg',
    pricePerKg: 225,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.9,
    reviewsCount: 156,
    purity: 'Premium Multi-Blend',
    moisture: '< 9.5% Max',
    origin: 'Cumbum Valley Organic Facility',
    protein: '12.5g / 100g',
    fiber: '9.5g / 100g',
    certification: 'NPOP Organic Certified',
    description: 'Balanced multi-millet gluten-free flour blend combining Ragi, Jowar, Bajra, Foxtail, and Barnyard flours. Perfect all-purpose flour.',
    image: '/finger_millet.png',
    premiumMetric: 'All-Purpose Multi-Blend',
    inStock: true
  },
  {
    id: 'premium-mix-flour',
    name: 'Organic Premium Mix Flour',
    tamilName: 'Premium Kalantha Maavu',
    scientificName: 'Multi-grain luxury mix',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Millet Flour',
    subCategory: 'Premium Stone-Ground Flours',
    moq: '1 kg',
    pricePerKg: 260,
    availableSizes: [0.5, 1, 2, 5],
    rating: 4.9,
    reviewsCount: 82,
    purity: 'Elite Blend w/ Amaranth',
    moisture: '< 9.0% Max',
    origin: 'Cumbum Valley Organic Facility',
    protein: '13.8g / 100g',
    fiber: '10.5g / 100g',
    certification: 'NPOP Organic Certified',
    description: 'A luxurious multi-millet blend enriched with organic amaranth flour and quinoa flour. Provides maximum protein density and gourmet flavor.',
    image: '/finger_millet.png',
    premiumMetric: 'Gourmet High-Protein Blend',
    inStock: true
  },
  {
    id: 'ragi-rava',
    name: 'Organic Ragi Millet Rava',
    tamilName: 'Ragi Rava',
    scientificName: 'Eleusine coracana',
    type: 'Major',
    form: 'Flakes',
    category: 'Millet Rava',
    subCategory: 'Breakfast Semolina / Rava',
    moq: '1 kg',
    pricePerKg: 175,
    availableSizes: [0.5, 1, 2],
    rating: 4.8,
    reviewsCount: 64,
    purity: 'Coarse Cleaned',
    moisture: '< 10.5% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '7.3g / 100g',
    fiber: '11.0g / 100g',
    certification: 'NPOP Organic',
    description: 'Coarsely ground organic Ragi semolina (rava). Excellent for highly nutritious, fiber-rich breakfast upma and healthy sweet halwa.',
    image: '/finger_millet.png',
    premiumMetric: 'Coarse Calcium Semolina',
    inStock: true
  },
  {
    id: 'jowar-rava',
    name: 'Organic Jowar Millet Rava',
    tamilName: 'Cholam Rava',
    scientificName: 'Sorghum bicolor',
    type: 'Major',
    form: 'Flakes',
    category: 'Millet Rava',
    subCategory: 'Breakfast Semolina / Rava',
    moq: '1 kg',
    pricePerKg: 190,
    availableSizes: [0.5, 1, 2],
    rating: 4.7,
    reviewsCount: 55,
    purity: 'Sortex Coarse',
    moisture: '< 10.8% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '10.2g / 100g',
    fiber: '6.6g / 100g',
    certification: 'NPOP Organic',
    description: 'Coarse Jowar semolina, clean and easy to cook. Offers a wonderful texture and premium glycemic control for daily porridge.',
    image: '/finger_millet.png',
    premiumMetric: 'Superior Glycemic Control',
    inStock: true
  },
  {
    id: 'bajra-rava',
    name: 'Organic Bajra Millet Rava',
    tamilName: 'Kambu Rava',
    scientificName: 'Pennisetum glaucum',
    type: 'Major',
    form: 'Flakes',
    category: 'Millet Rava',
    subCategory: 'Breakfast Semolina / Rava',
    moq: '1 kg',
    pricePerKg: 180,
    availableSizes: [0.5, 1, 2],
    rating: 4.8,
    reviewsCount: 71,
    purity: 'Coarse Cleaned',
    moisture: '< 11.0% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '11.5g / 100g',
    fiber: '8.3g / 100g',
    certification: 'NPOP Organic',
    description: 'Coarsely crushed pearl millet (Bajra) rava. Packed with iron, magnesium, and organic zinc. Perfect for warm traditional morning porridge.',
    image: '/finger_millet.png',
    premiumMetric: 'Essential Morning Minerals',
    inStock: true
  },
  {
    id: 'barnyard-rava',
    name: 'Organic Barnyard Millet Rava',
    tamilName: 'Kuthiraivali Rava',
    scientificName: 'Echinochloa frumentacea',
    type: 'Minor',
    form: 'Flakes',
    category: 'Millet Rava',
    subCategory: 'Breakfast Semolina / Rava',
    moq: '1 kg',
    pricePerKg: 220,
    availableSizes: [0.5, 1, 2],
    rating: 4.8,
    reviewsCount: 43,
    purity: 'Triple-Polished Coarse',
    moisture: '< 10.2% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '11.1g / 100g',
    fiber: '10.0g / 100g',
    certification: 'NPOP Organic',
    description: 'Pristine, organic barnyard millet semolina. Creates incredibly fluffy, digestible, gluten-free idli and upma.',
    image: '/finger_millet.png',
    premiumMetric: 'Premium Fluffy Upma',
    inStock: true
  },
  {
    id: 'foxtail-rava',
    name: 'Organic Foxtail Millet Rava',
    tamilName: 'Thinai Rava',
    scientificName: 'Setaria italica',
    type: 'Minor',
    form: 'Flakes',
    category: 'Millet Rava',
    subCategory: 'Breakfast Semolina / Rava',
    moq: '1 kg',
    pricePerKg: 210,
    availableSizes: [0.5, 1, 2],
    rating: 4.9,
    reviewsCount: 56,
    purity: 'Sortex Coarse Clean',
    moisture: '< 10.5% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '12.1g / 100g',
    fiber: '8.0g / 100g',
    certification: 'NPOP Organic',
    description: 'Golden-hued foxtail millet semolina rava. Sourced from high-density mountain farms, releasing a wonderful sweet nutty aroma.',
    image: '/finger_millet.png',
    premiumMetric: 'Aromatic Mountain Harvest',
    inStock: true
  },
  {
    id: 'kodo-rava',
    name: 'Organic Kodo Millet Rava',
    tamilName: 'Varagu Rava',
    scientificName: 'Paspalum scrobiculatum',
    type: 'Minor',
    form: 'Flakes',
    category: 'Millet Rava',
    subCategory: 'Breakfast Semolina / Rava',
    moq: '1 kg',
    pricePerKg: 220,
    availableSizes: [0.5, 1, 2],
    rating: 4.7,
    reviewsCount: 38,
    purity: 'Coarse Cleaned',
    moisture: '< 11.0% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '8.2g / 100g',
    fiber: '9.0g / 100g',
    certification: 'NPOP Organic',
    description: 'Rich, dark-tinted Kodo millet rava. Provides a gorgeous earthy flavor and superior complex carbs for blood sugar management.',
    image: '/finger_millet.png',
    premiumMetric: 'Earthy Low-GI Fiber',
    inStock: true
  },
  {
    id: 'little-rava',
    name: 'Organic Little Millet Rava',
    tamilName: 'Samai Rava',
    scientificName: 'Panicum sumatrense',
    type: 'Minor',
    form: 'Flakes',
    category: 'Millet Rava',
    subCategory: 'Breakfast Semolina / Rava',
    moq: '1 kg',
    pricePerKg: 205,
    availableSizes: [0.5, 1, 2],
    rating: 4.8,
    reviewsCount: 49,
    purity: 'Premium Coarse',
    moisture: '< 10.4% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '7.6g / 100g',
    fiber: '7.5g / 100g',
    certification: 'NPOP Organic',
    description: 'Organic Little millet rava, perfectly milled to cook rapidly. Perfect and light breakfast option for busy mornings.',
    image: '/finger_millet.png',
    premiumMetric: 'Rapid-Cook Lightweight',
    inStock: true
  },
  {
    id: 'browntop-rava',
    name: 'Organic Browntop Millet Rava',
    tamilName: 'Kula Samai Rava',
    scientificName: 'Urochloa ramosa',
    type: 'Minor',
    form: 'Flakes',
    category: 'Millet Rava',
    subCategory: 'Breakfast Semolina / Rava',
    moq: '1 kg',
    pricePerKg: 250,
    availableSizes: [0.5, 1, 2],
    rating: 4.9,
    reviewsCount: 29,
    purity: 'Sortex Coarse',
    moisture: '< 10.0% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '11.2g / 100g',
    fiber: '12.2g / 100g',
    certification: 'NPOP Organic',
    description: 'Exceptional coarse Browntop millet rava, highly recommended for maximum prebiotic gut fiber integration.',
    image: '/finger_millet.png',
    premiumMetric: 'Extreme Prebiotic Fiber',
    inStock: true
  },
  {
    id: 'proso-rava',
    name: 'Organic Proso Millet Rava',
    tamilName: 'Panivaragu Rava',
    scientificName: 'Panicum miliaceum',
    type: 'Minor',
    form: 'Flakes',
    category: 'Millet Rava',
    subCategory: 'Breakfast Semolina / Rava',
    moq: '1 kg',
    pricePerKg: 200,
    availableSizes: [0.5, 1, 2],
    rating: 4.6,
    reviewsCount: 31,
    purity: 'Coarse Cleaned',
    moisture: '< 11.2% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '12.3g / 100g',
    fiber: '7.6g / 100g',
    certification: 'NPOP Organic',
    description: 'Traditional proso millet rava, rich in protein and vitamins. Creates highly satiating and delicious cream-like warm porridges.',
    image: '/finger_millet.png',
    premiumMetric: 'High Satiety Nourishment',
    inStock: true
  },
  {
    id: 'red-rice-flakes',
    name: 'Organic Red Rice Poha',
    tamilName: 'Sigappu Aval',
    scientificName: 'Oryza sativa',
    type: 'Major',
    form: 'Flakes',
    category: 'Millet Flakes',
    subCategory: 'Heritage Poha / Flakes',
    moq: '500 g',
    pricePerKg: 180,
    availableSizes: [0.5, 1, 2],
    rating: 4.8,
    reviewsCount: 92,
    purity: 'Clean steam-pressed',
    moisture: '< 9.0% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '7.5g / 100g',
    fiber: '6.2g / 100g',
    certification: 'NPOP Organic',
    description: 'Heritage red rice grains parboiled and flattened into premium, easily digestible red poha (aval). Contains rich antioxidants in the red husk.',
    image: '/pearl_millet.png',
    premiumMetric: 'Rich Anthocyanin Base',
    inStock: true
  },
  {
    id: 'jowar-flakes',
    name: 'Organic Jowar Poha / Flakes',
    tamilName: 'Cholam Aval',
    scientificName: 'Sorghum bicolor',
    type: 'Major',
    form: 'Flakes',
    category: 'Millet Flakes',
    subCategory: 'Heritage Poha / Flakes',
    moq: '500 g',
    pricePerKg: 200,
    availableSizes: [0.5, 1, 2],
    rating: 4.7,
    reviewsCount: 53,
    purity: 'Flat-Rolled Sorted',
    moisture: '< 9.5% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '10.0g / 100g',
    fiber: '6.6g / 100g',
    certification: 'NPOP Organic',
    description: 'Flattened premium Jowar grain flakes. An exceptional, crunchy substitute for traditional corn flakes, loaded with digestion-friendly fibers.',
    image: '/pearl_millet.png',
    premiumMetric: 'Zero Added Corn Sugars',
    inStock: true
  },
  {
    id: 'bajra-flakes',
    name: 'Organic Bajra Poha / Flakes',
    tamilName: 'Kambu Aval',
    scientificName: 'Pennisetum glaucum',
    type: 'Major',
    form: 'Flakes',
    category: 'Millet Flakes',
    subCategory: 'Heritage Poha / Flakes',
    moq: '500 g',
    pricePerKg: 190,
    availableSizes: [0.5, 1, 2],
    rating: 4.8,
    reviewsCount: 68,
    purity: 'Steam-Rolled Pure',
    moisture: '< 9.2% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '11.5g / 100g',
    fiber: '8.4g / 100g',
    certification: 'NPOP Organic',
    description: 'Steam-rolled unpolished Bajra flakes. Extremely high-energy grain flakes, releasing a robust roasted nutty scent upon gentle cooking.',
    image: '/pearl_millet.png',
    premiumMetric: 'Roasted Nutty Energy',
    inStock: true
  },
  {
    id: 'ragi-flakes',
    name: 'Organic Ragi Poha / Flakes',
    tamilName: 'Ragi Aval',
    scientificName: 'Eleusine coracana',
    type: 'Major',
    form: 'Flakes',
    category: 'Millet Flakes',
    subCategory: 'Heritage Poha / Flakes',
    moq: '500 g',
    pricePerKg: 185,
    availableSizes: [0.5, 1, 2],
    rating: 4.9,
    reviewsCount: 114,
    purity: 'Precision Rolled',
    moisture: '< 9.0% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '7.1g / 100g',
    fiber: '11.0g / 100g',
    certification: 'NPOP Organic',
    description: 'Crimson-red finger millet grains precision flat-rolled. A highly delicious, calcium-dense breakfast snack ideal for health-conscious homes.',
    image: '/pearl_millet.png',
    premiumMetric: 'Elite Bone Enrichment',
    inStock: true
  },
  {
    id: 'kodo-flakes',
    name: 'Organic Kodo Poha / Flakes',
    tamilName: 'Varagu Aval',
    scientificName: 'Paspalum scrobiculatum',
    type: 'Minor',
    form: 'Flakes',
    category: 'Millet Flakes',
    subCategory: 'Heritage Poha / Flakes',
    moq: '500 g',
    pricePerKg: 215,
    availableSizes: [0.5, 1, 2],
    rating: 4.7,
    reviewsCount: 42,
    purity: 'Flat-Rolled Sorted',
    moisture: '< 9.5% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '8.1g / 100g',
    fiber: '8.8g / 100g',
    certification: 'NPOP Organic',
    description: 'Earthy and savory Kodo millet poha. Precision steam-pressed to retain therapeutic minerals, ideal for instant non-spiky carbohydrate recipes.',
    image: '/pearl_millet.png',
    premiumMetric: 'Glucose Stabilization',
    inStock: true
  },
  {
    id: 'foxtail-flakes-poha',
    name: 'Organic Foxtail Poha / Flakes',
    tamilName: 'Thinai Aval',
    scientificName: 'Setaria italica',
    type: 'Minor',
    form: 'Flakes',
    category: 'Millet Flakes',
    subCategory: 'Heritage Poha / Flakes',
    moq: '500 g',
    pricePerKg: 210,
    availableSizes: [0.5, 1, 2],
    rating: 4.8,
    reviewsCount: 59,
    purity: 'Steam-Rolled Premium',
    moisture: '< 9.4% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '12.0g / 100g',
    fiber: '7.8g / 100g',
    certification: 'NPOP Organic',
    description: 'Ancient Foxtail millet steam-rolled into light golden flakes. Superbly rich in vitamin B1 and complex proteins for highly functional mornings.',
    image: '/pearl_millet.png',
    premiumMetric: 'Rich in Vitamin B1',
    inStock: true
  },
  {
    id: 'siridhanya-combo-1kg',
    name: 'Organic Siridhanya Grains 1kg',
    tamilName: 'Siridhanya Combo',
    scientificName: 'Ancient grains bundle',
    type: 'Major',
    form: 'Raw Grain',
    category: 'Siridhanya',
    subCategory: 'Siridhanya Value Combos',
    moq: '5 kg',
    pricePerKg: 190,
    availableSizes: [5],
    rating: 4.9,
    reviewsCount: 245,
    purity: '5-Grain Elite Grains',
    moisture: '< 11.0% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '11.8g / 100g',
    fiber: '10.5g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Premium organic 5-grain siridhanya millet pack containing 1kg each of Foxtail, Kodo, Barnyard, Little, and Browntop grains. Maximum healing.',
    image: '/foxtail_millet.png',
    premiumMetric: '5-Grain Holistic Healing',
    inStock: true
  },
  {
    id: 'siridhanya-combo-500g',
    name: 'Organic Siridhanya Grains 500g',
    tamilName: 'Siridhanya Combo',
    scientificName: 'Ancient grains bundle',
    type: 'Major',
    form: 'Raw Grain',
    category: 'Siridhanya',
    subCategory: 'Siridhanya Value Combos',
    moq: '2.5 kg',
    pricePerKg: 196,
    availableSizes: [2.5],
    rating: 4.8,
    reviewsCount: 122,
    purity: '5-Grain Elite Grains',
    moisture: '< 11.0% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '11.8g / 100g',
    fiber: '10.5g / 100g',
    certification: 'NPOP / USDA Organic',
    description: 'Convenient organic 5-grain siridhanya millet pack containing 500g each of Foxtail, Kodo, Barnyard, Little, and Browntop grains.',
    image: '/foxtail_millet.png',
    premiumMetric: '5-Grain Compact Pack',
    inStock: true
  },
  {
    id: 'siridhanya-flour-combo-1kg',
    name: 'Organic Siridhanya Flours 1kg',
    tamilName: 'Siridhanya Maavu Combo',
    scientificName: 'Flours bundle',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Siridhanya',
    subCategory: 'Siridhanya Value Combos',
    moq: '5 kg',
    pricePerKg: 210,
    availableSizes: [5],
    rating: 4.9,
    reviewsCount: 189,
    purity: '5-Flour Stone Blend',
    moisture: '< 9.5% Max',
    origin: 'Cumbum Valley Foothills',
    protein: '11.5g / 100g',
    fiber: '10.2g / 100g',
    certification: 'NPOP Organic',
    description: 'Therapeutic pack of 5 organic stone-ground millet flours (Foxtail, Kodo, Barnyard, Little, Browntop), 1kg each. Complete gluten-free kitchen.',
    image: '/foxtail_millet.png',
    premiumMetric: '5-Flour Complete Kitchen',
    inStock: true
  },
  {
    id: 'siridhanya-flour-combo-500g',
    name: 'Organic Siridhanya Flours 500g',
    tamilName: 'Siridhanya Maavu Combo',
    scientificName: 'Flours bundle',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Siridhanya',
    subCategory: 'Siridhanya Value Combos',
    moq: '2.5 kg',
    pricePerKg: 220,
    availableSizes: [2.5],
    rating: 4.8,
    reviewsCount: 94,
    purity: '5-Flour Stone Blend',
    moisture: '< 9.5% Max',
    origin: 'Cumbum Valley Foothills',
    protein: '11.5g / 100g',
    fiber: '10.2g / 100g',
    certification: 'NPOP Organic',
    description: 'Convenient pack of 5 organic stone-ground millet flours (Foxtail, Kodo, Barnyard, Little, Browntop), 500g each.',
    image: '/foxtail_millet.png',
    premiumMetric: '5-Flour Compact Kitchen',
    inStock: true
  },
  {
    id: 'siridhanya-rava-combo-1kg',
    name: 'Organic Siridhanya Rava 1kg',
    tamilName: 'Siridhanya Rava Combo',
    scientificName: 'Rava bundle',
    type: 'Major',
    form: 'Flakes',
    category: 'Siridhanya',
    subCategory: 'Siridhanya Value Combos',
    moq: '5 kg',
    pricePerKg: 220,
    availableSizes: [5],
    rating: 4.9,
    reviewsCount: 167,
    purity: '5-Rava Premium',
    moisture: '< 10.0% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '11.2g / 100g',
    fiber: '10.8g / 100g',
    certification: 'NPOP Organic',
    description: '5-pack organic premium coarsely ground siridhanya semolina (rava), 1kg each. Great for diverse highly nutritive upma and idli.',
    image: '/foxtail_millet.png',
    premiumMetric: '5-Rava Ultimate Breakfast',
    inStock: true
  },
  {
    id: 'siridhanya-rava-combo-500g',
    name: 'Organic Siridhanya Rava 500g',
    tamilName: 'Siridhanya Rava Combo',
    scientificName: 'Rava bundle',
    type: 'Major',
    form: 'Flakes',
    category: 'Siridhanya',
    subCategory: 'Siridhanya Value Combos',
    moq: '2.5 kg',
    pricePerKg: 232,
    availableSizes: [2.5],
    rating: 4.8,
    reviewsCount: 78,
    purity: '5-Rava Premium',
    moisture: '< 10.0% Max',
    origin: 'Cumbum Valley, Tamil Nadu',
    protein: '11.2g / 100g',
    fiber: '10.8g / 100g',
    certification: 'NPOP Organic',
    description: 'Convenient 5-pack organic premium coarsely ground siridhanya semolina (rava), 500g each.',
    image: '/foxtail_millet.png',
    premiumMetric: '5-Rava Compact Breakfast',
    inStock: true
  },
  {
    id: 'millet-ladoo-combo',
    name: 'Millet Laddoo Premium Combo',
    tamilName: 'Laddoo Combo',
    scientificName: 'Sweets bundle',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Combos',
    subCategory: 'Laddoo & Breakfast Combos',
    moq: '1 kg',
    pricePerKg: 420,
    availableSizes: [0.5, 1, 2],
    rating: 4.9,
    reviewsCount: 204,
    purity: 'Pure Ghee Sweets',
    moisture: '< 8.0% Max',
    origin: 'Urban Monk Kitchens',
    protein: '8.5g / 100g',
    fiber: '6.0g / 100g',
    certification: 'FSSAI Certified',
    description: 'Assorted pure A2 ghee-laden millet laddoos prepared with sprouted Ragi, Bajra, and Jowar flours, sweetened gently with organic palm jaggery.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Sweetened w/ Palm Jaggery',
    inStock: true
  },
  {
    id: 'bajra-ragi-ladoo-combo',
    name: 'Bajra & Ragi Laddoo Combo',
    tamilName: 'Kambu Ragi Laddoo',
    scientificName: 'Sweets bundle',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Combos',
    subCategory: 'Laddoo & Breakfast Combos',
    moq: '1 kg',
    pricePerKg: 380,
    availableSizes: [0.5, 1],
    rating: 4.8,
    reviewsCount: 134,
    purity: 'Pure Ghee Sweets',
    moisture: '< 8.2% Max',
    origin: 'Urban Monk Kitchens',
    protein: '9.0g / 100g',
    fiber: '7.5g / 100g',
    certification: 'FSSAI Certified',
    description: 'Delicious iron and calcium dense organic laddoos made with pure pearl millet and finger millet stone-ground flours. Excellent healthy kids treat.',
    image: '/foxtail_millet.png',
    premiumMetric: 'A2 Ghee Richness',
    inStock: true
  },
  {
    id: 'jowar-bajra-ladoo-combo',
    name: 'Jowar & Bajra Laddoo Combo',
    tamilName: 'Cholam Kambu Laddoo',
    scientificName: 'Sweets bundle',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Combos',
    subCategory: 'Laddoo & Breakfast Combos',
    moq: '1 kg',
    pricePerKg: 390,
    availableSizes: [0.5, 1],
    rating: 4.8,
    reviewsCount: 110,
    purity: 'Pure Ghee Sweets',
    moisture: '< 8.0% Max',
    origin: 'Urban Monk Kitchens',
    protein: '9.2g / 100g',
    fiber: '6.8g / 100g',
    certification: 'FSSAI Certified',
    description: 'Highly energy-rich sorghum and pearl millet laddoos prepared with cold-pressed cardamom extract and rich luxury cashew nuts.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Pure Cashew & Cardamom',
    inStock: true
  },
  {
    id: 'millet-breakfast-mix-combo',
    name: 'Organic Millet Breakfast Mix',
    tamilName: 'Kaalai Unavu Combo',
    scientificName: 'Mixes bundle',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Combos',
    subCategory: 'Laddoo & Breakfast Combos',
    moq: '1 kg',
    pricePerKg: 450,
    availableSizes: [1, 2],
    rating: 4.9,
    reviewsCount: 178,
    purity: 'Instant Mix Pack',
    moisture: '< 7.5% Max',
    origin: 'Cumbum Valley Organic Facility',
    protein: '11.0g / 100g',
    fiber: '9.0g / 100g',
    certification: 'NPOP / FSSAI Certified',
    description: 'Complete organic quick-cook breakfast mix collection containing Ragi Idli Mix, Jowar Dosa Mix, and Bajra Pongal Mix. Clean nutrition in 10 mins.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Nutritious 10-Min Meals',
    inStock: true
  },
  {
    id: 'millet-idly-dosa-combo',
    name: 'Organic Idly & Rava Dosa Combo',
    tamilName: 'Idly Dosa Rava Combo',
    scientificName: 'Mixes bundle',
    type: 'Major',
    form: 'Flakes',
    category: 'Combos',
    subCategory: 'Laddoo & Breakfast Combos',
    moq: '1 kg',
    pricePerKg: 430,
    availableSizes: [1, 2],
    rating: 4.8,
    reviewsCount: 96,
    purity: 'Instant Mix Pack',
    moisture: '< 7.8% Max',
    origin: 'Cumbum Valley Organic Facility',
    protein: '10.8g / 100g',
    fiber: '9.2g / 100g',
    certification: 'NPOP / FSSAI Certified',
    description: 'Perfect breakfast combo of unpolished organic millet-based idly mixes and crispy rava dosa semolina mixes. Very high fiber yield.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Super Crispy Texture',
    inStock: true
  },
  {
    id: 'dosa-idly-batter-combo',
    name: 'Premium Dosa Idly Batter Combo',
    tamilName: 'Batter Combo',
    scientificName: 'Fresh Fermented Blend',
    type: 'Major',
    form: 'Raw Grain',
    category: 'Combos',
    subCategory: 'Laddoo & Breakfast Combos',
    moq: '2 kg',
    pricePerKg: 125,
    availableSizes: [2],
    rating: 4.9,
    reviewsCount: 312,
    purity: 'Freshly Fermented',
    moisture: 'Liquid Batter',
    origin: 'Bengaluru / Bangalore Fresh Hub',
    protein: '8.2g / 100g',
    fiber: '6.5g / 100g',
    certification: 'Freshly Prepared (Bengaluru Only)',
    description: 'Elite quality freshly ground stone-fermented multi-millet dosa and idly batter. Pre-fermented under optical temperature check.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Fully Organic Ferment',
    inStock: true
  },
  {
    id: 'millet-dosa-idli-batter-combo',
    name: 'Millet Dosa Idli Batter Combo',
    tamilName: 'Millet Batter Combo',
    scientificName: 'Fresh Fermented Blend',
    type: 'Major',
    form: 'Raw Grain',
    category: 'Combos',
    subCategory: 'Laddoo & Breakfast Combos',
    moq: '2 kg',
    pricePerKg: 140,
    availableSizes: [2],
    rating: 4.9,
    reviewsCount: 220,
    purity: 'Freshly Fermented',
    moisture: 'Liquid Batter',
    origin: 'Bengaluru / Bangalore Fresh Hub',
    protein: '8.8g / 100g',
    fiber: '7.8g / 100g',
    certification: 'Freshly Prepared (Bengaluru Only)',
    description: 'Fresh 5-millet stone-ground idli and dosa batter. Naturally rich in prebiotics, creating crisp golden dosas and feather-light idlis.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Feather-Light Premium Idlis',
    inStock: true
  },
  {
    id: 'millet-noodles-pasta',
    name: 'Organic Millet Noodles & Pasta',
    tamilName: 'Sevai & Pasta',
    scientificName: 'Processed noodles',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Ready to Cook',
    subCategory: 'Nourishing Instant Mixes',
    moq: '1 kg',
    pricePerKg: 160,
    availableSizes: [0.5, 1, 2],
    rating: 4.8,
    reviewsCount: 139,
    purity: 'Gluten-Free Extruded',
    moisture: '< 8.0% Max',
    origin: 'Cumbum Valley Organic Facility',
    protein: '11.5g / 100g',
    fiber: '8.5g / 100g',
    certification: 'NPOP Organic / FSSAI',
    description: 'Naturally air-dried gluten-free multi-millet noodles and pasta shapes. Contain zero refined flour (maida) or artificial binders.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Zero Maida or Binders',
    inStock: true
  },
  {
    id: 'breakfast-mixes',
    name: 'Heritage Millet Breakfast Mixes',
    tamilName: 'Instant Idli Mix',
    scientificName: 'Instant Mix Blend',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Ready to Cook',
    subCategory: 'Nourishing Instant Mixes',
    moq: '1 kg',
    pricePerKg: 180,
    availableSizes: [0.5, 1, 2],
    rating: 4.7,
    reviewsCount: 88,
    purity: 'Spiced Ready Mix',
    moisture: '< 7.8% Max',
    origin: 'Cumbum Valley Foothills',
    protein: '10.5g / 100g',
    fiber: '9.0g / 100g',
    certification: 'FSSAI Certified',
    description: 'Heritage spiced instant breakfast mixes, loaded with organic cashews, mustard seeds, curry leaves, and unpolished kodo millet semolina.',
    image: '/foxtail_millet.png',
    premiumMetric: 'Pre-Spiced Organic Mix',
    inStock: true
  },
  {
    id: 'healthy-drinks',
    name: 'Organic Healthy Millet Drinks',
    tamilName: 'Millet Sathumaavu Mix',
    scientificName: 'Sprouted health mix',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Ready to Cook',
    subCategory: 'Nourishing Instant Mixes',
    moq: '1 kg',
    pricePerKg: 220,
    availableSizes: [0.5, 1, 2],
    rating: 4.9,
    reviewsCount: 165,
    purity: 'Sprouted 100% Raw',
    moisture: '< 6.5% Max',
    origin: 'Cumbum Valley Foothills',
    protein: '13.0g / 100g',
    fiber: '10.5g / 100g',
    certification: 'NPOP Organic / FSSAI',
    description: 'Traditional Sprouted Millet Sathumaavu Health Drink Mix, crafted with 10 sprouted grains and luxury nuts. Ultimate organic nourishment.',
    image: '/foxtail_millet.png',
    premiumMetric: '10 Sprouted Grains',
    inStock: true
  },
  {
    id: 'millet-sweets',
    name: 'Organic Traditional Millet Sweets',
    tamilName: 'Millet Halwa & Athirasam',
    scientificName: 'Gourmet sweets',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Sweets & Snacks',
    subCategory: 'Savoury Delights & Starters',
    moq: '1 kg',
    pricePerKg: 350,
    availableSizes: [0.5, 1],
    rating: 4.9,
    reviewsCount: 94,
    purity: 'Organic Jaggery Sweets',
    moisture: '< 10.0% Max',
    origin: 'Urban Monk Kitchens',
    protein: '6.5g / 100g',
    fiber: '5.5g / 100g',
    certification: 'FSSAI Certified',
    description: 'Luxury organic sweets prepared with sprouted finger millet, cardamom, and cold-pressed sesame oil. Melt-in-the-mouth heritage sweets.',
    image: '/finger_millet.png',
    premiumMetric: 'Cold-Pressed Cardamom',
    inStock: true
  },
  {
    id: 'digestive-seed-cocktail',
    name: 'Digestive Seed Cocktail Mix',
    tamilName: 'Digestive Mix',
    scientificName: 'Seeds blend',
    type: 'Major',
    form: 'Raw Grain',
    category: 'Sweets & Snacks',
    subCategory: 'Savoury Delights & Starters',
    moq: '500 g',
    pricePerKg: 290,
    availableSizes: [0.5, 1],
    rating: 4.8,
    reviewsCount: 102,
    purity: 'Roasted seed blend',
    moisture: '< 5.0% Max',
    origin: 'Cumbum Valley Facility',
    protein: '16.5g / 100g',
    fiber: '12.0g / 100g',
    certification: 'FSSAI Certified',
    description: 'Therapeutic digestive seed mix combining organic sesame seeds, flax seeds, roasted millet grains, fennel, and spiced carom.',
    image: '/finger_millet.png',
    premiumMetric: 'Active Spiced Carom',
    inStock: true
  },
  {
    id: 'savoury-snacks',
    name: 'Heritage Millet Savoury Snacks',
    tamilName: 'Millet Murukku & Karasev',
    scientificName: 'Savoury snacks',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Sweets & Snacks',
    subCategory: 'Savoury Delights & Starters',
    moq: '500 g',
    pricePerKg: 190,
    availableSizes: [0.5, 1],
    rating: 4.7,
    reviewsCount: 88,
    purity: 'Cold-pressed fried',
    moisture: '< 4.5% Max',
    origin: 'Urban Monk Kitchens',
    protein: '10.2g / 100g',
    fiber: '8.0g / 100g',
    certification: 'FSSAI Certified',
    description: 'Deliciously crunchy heritage murukku and ribbon karasev snacks prepared using organic Ragi flour, black gram, and pure groundnut oil.',
    image: '/finger_millet.png',
    premiumMetric: 'Cold-Pressed Groundnut Oil',
    inStock: true
  },
  {
    id: 'millet-podi',
    name: 'Traditional Millet Spiced Podi',
    tamilName: 'Millet Idli Podi',
    scientificName: 'Spiced lentil powder',
    type: 'Major',
    form: 'Fine Flour',
    category: 'Sweets & Snacks',
    subCategory: 'Savoury Delights & Starters',
    moq: '500 g',
    pricePerKg: 180,
    availableSizes: [0.5, 1],
    rating: 4.8,
    reviewsCount: 77,
    purity: 'Stone-Ground Spiced',
    moisture: '< 6.0% Max',
    origin: 'Urban Monk Kitchens',
    protein: '14.0g / 100g',
    fiber: '11.0g / 100g',
    certification: 'FSSAI Certified',
    description: 'Gourmet roasted idli podi spice blend enriched with stone-ground toasted black gram, organic curry leaves, red chilies, and pearl millets.',
    image: '/finger_millet.png',
    premiumMetric: 'Gourmet Toasted Curry Leaves',
    inStock: true
  },
  {
    id: 'fresh-batters',
    name: 'Fresh Stone-Ground Batters',
    tamilName: 'Fresh Batter',
    scientificName: 'Fermented Batter',
    type: 'Major',
    form: 'Raw Grain',
    category: 'Sweets & Snacks',
    subCategory: 'Savoury Delights & Starters',
    moq: '1 kg',
    pricePerKg: 120,
    availableSizes: [1],
    rating: 4.9,
    reviewsCount: 145,
    purity: 'Optimum pre-fermentation',
    moisture: 'Liquid Batter',
    origin: 'Bengaluru / Bangalore Fresh Hub',
    protein: '8.0g / 100g',
    fiber: '7.0g / 100g',
    certification: 'Fresh Prepared (Bangalore Only)',
    description: 'Organic unpolished parboiled rice and multi-millet stone-ground fresh batter. Delivers outstandingly crisp crepes and soft traditional idlis.',
    image: '/finger_millet.png',
    premiumMetric: 'Ancient Stone-Ground',
    inStock: true
  }
];

const INITIAL_ORDERS = [
  {
    id: 'ORD-88901',
    items: [
      {
        id: 'pearl-grain-1',
        product: MILLETS_DATABASE[0],
        quantity: 2,
        size: 1, // 1 MT
        price: 180000 // ₹1,80,000 per MT
      },
      {
        id: 'finger-flour-2',
        product: MILLETS_DATABASE[1],
        quantity: 1,
        size: 2, // 2 MT
        price: 320000 // ₹3,20,000
      }
    ],
    total: 500000,
    shippingDetails: {
      signatory: 'Alexander Vance',
      company: 'Vanguard Foods Group',
      email: 'a.vance@vanguardfoods.com',
      phone: '+1 (555) 234-8902',
      address: 'Port of Hamburg Terminal 3, Hamburg, Germany',
      pincode: '20457',
      timeline: 'Sea Freight - 20FT FCL'
    },
    status: 'Logged',
    createdAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
    accountExecutive: 'Siddharth R.',
    trackingNotes: 'Export documentation cleared. Phytosanitary certificates appended. Container sealing initialized under optical monitoring.'
  },
  {
    id: 'ORD-88742',
    items: [
      {
        id: 'foxtail-grain-0.5',
        product: MILLETS_DATABASE[2],
        quantity: 4,
        size: 0.5, // 500 kg
        price: 105000 // ₹1,05,000
      }
    ],
    total: 420000,
    shippingDetails: {
      signatory: 'Elisa Moreno',
      company: 'NaturaCéleste S.A.',
      email: 'e.moreno@naturaceleste.fr',
      phone: '+33 1 42 68 53 00',
      address: 'Port of Marseille, Marseille, France',
      pincode: '13001',
      timeline: 'Sea Freight - 20FT FCL'
    },
    status: 'Processing',
    createdAt: new Date(Date.now() - 19.2 * 60 * 60 * 1000).toISOString(),
    accountExecutive: 'Priya Narayanan',
    trackingNotes: 'Optical purity test passed (99.9% clean). Vacuum sealing verified. Pre-assigned to temperature-controlled ocean freight.'
  }
];

export const calculateTieredPricePerKg = (basePricePerKg, totalWeight) => {
  if (totalWeight < 100) {
    return Math.round(basePricePerKg * 1.25); // +25% markup for small orders (under 100kg)
  } else if (totalWeight >= 100 && totalWeight < 500) {
    return basePricePerKg; // Actual B2B base rate
  } else if (totalWeight >= 500 && totalWeight < 1000) {
    return Math.round(basePricePerKg * 0.95); // 5% bulk discount (500kg+)
  } else {
    return Math.round(basePricePerKg * 0.90); // 10% super exporter discount (1000kg+)
  }
};

export const calculateCartItemPrice = (product, size, quantity) => {
  const totalWeight = size * quantity;
  const ratePerKg = calculateTieredPricePerKg(product.pricePerKg, totalWeight);
  return Math.round(ratePerKg * size);
};

const overrideProducts = MILLETS_DATABASE.map(p => ({
  ...p,
  availableSizes: [50, 100, 500, 1000],
  moq: '50 kg'
}));

export const AppProvider = ({ children }) => {
  const [activePage, setActivePage] = useState('landing'); // 'landing', 'shop', 'checkout', 'portal', 'admin'
  const [activeMobileTab, setActiveMobileTab] = useState('home'); // 'home', 'catalog', 'portal', 'admin'
  
  const [cart, setCart] = useState(() => {
    const saved = localStorage.getItem('cumbum_cart');
    return saved ? JSON.parse(saved) : [];
  });
  
  const [orders, setOrders] = useState(() => {
    const saved = localStorage.getItem('cumbum_orders');
    return saved ? JSON.parse(saved) : INITIAL_ORDERS;
  });
  
  const [isCartOpen, setIsCartOpen] = useState(false);
  const [isDetailsOpen, setIsDetailsOpen] = useState(false);
  const [activeProduct, setActiveProduct] = useState(null);
  const [lastCompletedOrder, setLastCompletedOrder] = useState(null);
  const [isCategoryDrawerOpen, setIsCategoryDrawerOpen] = useState(false);
  const [selectedCategory, setSelectedCategory] = useState('All');
  const [selectedSubCategory, setSelectedSubCategory] = useState('All');

  // Sync to local storage
  useEffect(() => {
    localStorage.setItem('cumbum_cart', JSON.stringify(cart));
  }, [cart]);

  useEffect(() => {
    localStorage.setItem('cumbum_orders', JSON.stringify(orders));
  }, [orders]);

  // Sync mobile tabs
  useEffect(() => {
    const tabMap = {
      'home': 'landing',
      'catalog': 'shop',
      'story': 'story',
      'portal': 'portal',
      'admin': 'admin'
    };
    setActivePage(tabMap[activeMobileTab]);
  }, [activeMobileTab]);

  const addToCart = (product, quantity = 1, size = 100) => {
    triggerHaptic(20);
    setCart((prev) => {
      const existingIdx = prev.findIndex(
        (item) => item.product.id === product.id && item.size === size
      );

      if (existingIdx > -1) {
        const nextCart = [...prev];
        const nextQty = nextCart[existingIdx].quantity + quantity;
        nextCart[existingIdx].quantity = nextQty;
        nextCart[existingIdx].price = calculateCartItemPrice(product, size, nextQty);
        return nextCart;
      }

      const itemPrice = calculateCartItemPrice(product, size, quantity);
      const cartItemId = `${product.id}-${size}-${Date.now()}`;
      return [...prev, { id: cartItemId, product, quantity, size, price: itemPrice }];
    });
  };

  const removeFromCart = (cartItemId) => {
    triggerHaptic(15);
    setCart((prev) => prev.filter((item) => item.id !== cartItemId));
  };

  const updateCartQuantity = (cartItemId, newQty) => {
    if (newQty <= 0) {
      removeFromCart(cartItemId);
      return;
    }
    triggerHaptic(10);
    setCart((prev) =>
      prev.map((item) =>
        item.id === cartItemId
          ? {
              ...item,
              quantity: newQty,
              price: calculateCartItemPrice(item.product, item.size, newQty)
            }
          : item
      )
    );
  };

  const clearCart = () => {
    setCart([]);
  };

  const submitCheckout = (shippingDetails) => {
    triggerHaptic(30);
    const newId = `ORD-${Math.floor(10000 + Math.random() * 90000)}`;
    const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
    const newOrder = {
      id: newId,
      items: [...cart],
      total: subtotal,
      shippingDetails,
      status: 'Logged',
      createdAt: new Date().toISOString(),
      accountExecutive: 'Siddharth R.',
      trackingNotes: 'Secure payment cleared. Packaging lines packaging your heritage millet grains.'
    };

    setOrders((prev) => [newOrder, ...prev]);
    setLastCompletedOrder(newOrder);
    clearCart();
    return newOrder;
  };

  const updateOrderStatus = (id, newStatus, extraData = {}) => {
    setOrders((prev) =>
      prev.map((ord) =>
        ord.id === id
          ? {
              ...ord,
              status: newStatus,
              ...extraData,
            }
          : ord
      )
    );
  };

  const deleteOrder = (id) => {
    setOrders((prev) => prev.filter((ord) => ord.id !== id));
  };

  const triggerHaptic = (ms = 15) => {
    if (typeof window !== 'undefined' && window.navigator && window.navigator.vibrate) {
      window.navigator.vibrate(ms);
    }
  };

  return (
    <AppContext.Provider
      value={{
        activePage,
        setActivePage,
        activeMobileTab,
        setActiveMobileTab,
        products: overrideProducts,
        cart,
        orders,
        addToCart,
        removeFromCart,
        updateCartQuantity,
        clearCart,
        submitCheckout,
        updateOrderStatus,
        deleteOrder,
        isCartOpen,
        setIsCartOpen,
        isDetailsOpen,
        setIsDetailsOpen,
        activeProduct,
        setActiveProduct,
        lastCompletedOrder,
        setLastCompletedOrder,
        triggerHaptic,
        isCategoryDrawerOpen,
        setIsCategoryDrawerOpen,
        selectedCategory,
        setSelectedCategory,
        selectedSubCategory,
        setSelectedSubCategory
      }}
    >
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
};
